name: flutter_music_player
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_navigation_bar: ^0.2.6
  sleek_circular_slider: ^1.1.0
  shared_preferences: ^0.5.7+3
  permission_handler: ^5.0.1
  cupertino_icons: ^0.1.3
  flutter_sound: ^5.1.0
  audioplayers: ^0.15.1
  file_picker: ^1.12.0
  flutter_modular:
  flare_flutter:
  flutter_mobx:
  mobx:

dev_dependencies:
  build_runner:
  mobx_codegen:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/app/assets/animations/
    - lib/app/assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: lib/app/assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: lib/app/assets/fonts/open_sans/OpenSans-Light.ttf
        - weight: 200

scripts:
  mobw: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs